# Generated by Django 5.2.7 on 2026-05-18 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsrecord",
            name="diastolic",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Normal: 60-80 mmHg",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(40),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vitalsrecord",
            name="glucose_type",
            field=models.CharField(
                blank=True,
                choices=[("FBS", "Fasting (FBS)"), ("RBS", "Random (RBS)")],
                default="RBS",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="vitalsrecord",
            name="glucose_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Normal FBS: 3.9-5.5, RBS: <7.8 mmol/L",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(40.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vitalsrecord",
            name="pulse",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Normal: 60-100 bpm",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(220),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vitalsrecord",
            name="systolic",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Normal: 90-120 mmHg",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vitalsrecord",
            name="temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Normal: 36.1-37.2 C",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30.0),
                    django.core.validators.MaxValueValidator(45.0),
                ],
            ),
        ),
    ]
