# Generated by Django 5.2.7 on 2026-05-18 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[\\+]?[\\d\\s\\-]{7,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("0-5", "0-5"),
                            ("6-12", "6-12"),
                            ("13-17", "13-17"),
                            ("18-25", "18-25"),
                            ("26-35", "26-35"),
                            ("36-45", "36-45"),
                            ("46-55", "46-55"),
                            ("56-65", "56-65"),
                            ("65+", "65+"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                (
                    "genotype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AA", "AA"),
                            ("AS", "AS"),
                            ("SS", "SS"),
                            ("AC", "AC"),
                            ("SC", "SC"),
                            ("CC", "CC"),
                        ],
                        default="",
                        max_length=3,
                    ),
                ),
                ("known_conditions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="patients_pa_last_na_1b32a7_idx",
                    ),
                ],
            },
        ),
    ]
