# Generated by Django 5.2.7 on 2026-05-18 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VitalsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic",
                    models.PositiveIntegerField(
                        help_text="Normal: 90-120 mmHg",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveIntegerField(
                        help_text="Normal: 60-80 mmHg",
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        help_text="Normal: 60-100 bpm",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Normal: 36.1-37.2 C",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(30.0),
                            django.core.validators.MaxValueValidator(45.0),
                        ],
                    ),
                ),
                (
                    "glucose_type",
                    models.CharField(
                        choices=[("FBS", "Fasting (FBS)"), ("RBS", "Random (RBS)")],
                        default="RBS",
                        max_length=3,
                    ),
                ),
                (
                    "glucose_value",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Normal FBS: 3.9-5.5, RBS: <7.8 mmol/L",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(40.0),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("medications", models.TextField(blank=True, default="")),
                ("correction_requested", models.BooleanField(default=False)),
                ("correction_reason", models.TextField(blank=True, default="")),
                ("correction_approved", models.BooleanField(default=False)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitalsrecord_set",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-recorded_at"],
                        name="vitals_vita_patient_f59a54_idx",
                    )
                ],
            },
        ),
    ]
