# Generated by Django 5.2.7 on 2026-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="known_conditions",
            field=models.TextField(
                blank=True, default="", help_text="Comma-separated list of conditions"
            ),
        ),
    ]
