# Generated by Django 5.2.10 on 2026-05-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_known_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
