# Generated by Django 5.2.10 on 2026-05-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age_range',
            field=models.CharField(blank=True, choices=[('0-5', '0-5'), ('6-12', '6-12'), ('13-17', '13-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('56-65', '56-65'), ('65+', '65+')], max_length=5),
        ),
    ]
